version: '3'

services:
  mongodb_auth_service:
    container_name: mongodb_auth_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authService
      - MONGO_INITDB_ROOT_PASSWORD=authService
    ports:
      - "27017:27017"
    volumes:
      - mongodb-authService-data:/data/db

  mongo-express-auth:
    container_name: mongo-express-auth
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://authService:authService@mongodb_auth_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=authService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=authService
    depends_on:
      - mongodb_auth_service
    ports:
      - "8081:8081"

  auth-service:
    container_name: auth-service
    build: ./ride-off-smart-ride-app-auth-service
    depends_on:
      - mongodb_auth_service
    ports:
      - "3000:3000"


  mongodb_verification_service:
    container_name: mongodb_verification_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=verificationService
      - MONGO_INITDB_ROOT_PASSWORD=verificationService
    ports:
      - "27018:27017" # 27018 = host port, 27017 = container port
    volumes:
      - mongodb-verificationService-data:/data/db

  mongo-express-verification:
    container_name: mongo-express-verification
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://verificationService:verificationService@mongodb_verification_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=verificationService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=verificationService
    depends_on:
      - mongodb_verification_service
    ports:
      - "8082:8081"

  verification-service:
    container_name: verification-service
    build: ./ride-off-smart-ride-app-verification-service
    depends_on:
      - mongodb_verification_service
    ports:
      - "3001:3000"

volumes:
  mongodb-authService-data:
    driver: local

  mongodb-verificationService-data:
    driver: local